name: Build CI Containers

on:
  workflow_dispatch:
  workflow_call:

permissions:
  contents: read

jobs:
  build-ci-linux-arm64:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8

      - name: Lowercase Registry Owner
        id: owner
        shell: bash
        run: |
          echo "owner=${GITHUB_REPOSITORY_OWNER,,}" >> "$GITHUB_OUTPUT"
        env:
          GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@c7c53464625b32c7a7e944ae62b3e17d2b600130

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f

      - name: Login to GitHub Container Registry
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83
        with:
          context: .
          file: .github/docker/ci-linux-arm64.Dockerfile
          platforms: linux/arm64
          push: true
          tags: ghcr.io/${{ steps.owner.outputs.owner }}/archive_r/ci-linux-arm64:latest

  build-ci-linux-arm64-cross:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8

      - name: Lowercase Registry Owner
        id: owner
        shell: bash
        run: |
          echo "owner=${GITHUB_REPOSITORY_OWNER,,}" >> "$GITHUB_OUTPUT"
        env:
          GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f

      - name: Login to GitHub Container Registry
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83
        with:
          context: .
          file: .github/docker/ci-linux-arm64-cross.Dockerfile
          platforms: linux/amd64
          push: true
          tags: ghcr.io/${{ steps.owner.outputs.owner }}/archive_r/ci-linux-arm64-cross:latest

  build-ci-windows-msvc:
    runs-on: windows-2022
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8

      - name: Lowercase Registry Owner
        id: owner
        shell: bash
        run: |
          echo "owner=${GITHUB_REPOSITORY_OWNER,,}" >> "$GITHUB_OUTPUT"
        env:
          GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        shell: pwsh
        run: |
          $ImageName = "ghcr.io/${{ steps.owner.outputs.owner }}/archive_r/ci-windows-msvc:latest"
          docker build -t $ImageName -f .github/docker/ci-windows-msvc.Dockerfile .
          docker push $ImageName

  build-ci-windows-mingw:
    runs-on: windows-2022
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8

      - name: Lowercase Registry Owner
        id: owner
        shell: bash
        run: |
          echo "owner=${GITHUB_REPOSITORY_OWNER,,}" >> "$GITHUB_OUTPUT"
        env:
          GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        shell: pwsh
        run: |
          $ImageName = "ghcr.io/${{ steps.owner.outputs.owner }}/archive_r/ci-windows-mingw:latest"
          docker build -t $ImageName -f .github/docker/ci-windows-mingw.Dockerfile .
          docker push $ImageName
