name: Build Containers

on:
  workflow_dispatch:
  workflow_call:

permissions:
  contents: read

jobs:
  build-ci-containers:
    name: Build CI Containers
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/build-ci-containers.yml

  build-wheel-containers:
    name: Build Wheel Containers
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/build-wheel-containers.yml

